export const Portfolios = [
    {
        id: 0,
        title: "허니머니",
        feature: [
            "지출·수입 등록,수정,삭제 기능",
            "차트",
            "달력",
            "이미지업로드",
            "월 지출·수입 계산",
        ],
        skills: [
            "axios",
            "nivo",
            "react-hook-form",
            "react-router-dom",
            "yup",
            "styled-components",
            "Tailwind CSS",
        ],
        img: "/images/shoppy.png",
        iframe: "https://www.youtube.com/embed/ugjnXVgQ3gY",
        site: "none",
        git: "https://github.com/tmdgus95/accountbook",
        youtube: "https://www.youtube.com/watch?v=ugjnXVgQ3gY",
    },
    {
        id: 1,
        title: "담화마켓",
        feature: [
            "상품추가",
            "장바구니 담기",
            "장바구니 수량 변경",
            "이미지업로드",
        ],
        skills: [
            "tanstack/react-query",
            "axios",
            "react-router-dom",
            "react-spinners",
            "Tailwind CSS",
        ],
        img: "/images/담화마켓.PNG",
        iframe: "https://www.youtube.com/embed/_1uRGkBbhUc",
        site: "none",
        git: "https://github.com/tmdgus95/damhwamarket",
        youtube: "https://www.youtube.com/watch?v=_1uRGkBbhUc",
    },

    {
        id: 2,
        title: "Shoppy",
        feature: [
            "상품추가",
            "장바구니 담기",
            "장바구니 수량 변경",
            "이미지업로드",
        ],
        skills: [
            "파이어베이스",
            "리액트아이콘",
            "uuid",
            "리액트 쿼리",
            "react-router-dom",
            "Tailwind CSS",
        ],
        img: "/images/shoppy.png",
        site: "https://sparkling-axolotl-5d4a63.netlify.app",
        git: "https://github.com/tmdgus95/Shoppy",
        youtube: "none",
    },
    {
        id: 3,
        title: "todo",
        feature: ["todo추가", "todo삭제", "필터별 todo보기", "다크모드"],
        skills: ["PostCss", "리액트아이콘"],
        img: "/images/todo.PNG",
        site: "https://taupe-begonia-74d622.netlify.app/",
        git: "https://github.com/tmdgus95/todo",
        youtube: "none",
    },
];
